name: Auto Assign PR Author

on:
  pull_request:
    types: [opened]

jobs:
  assign:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      issues: write
    steps:
      - name: Assign PR author as assignee
        uses: actions/github-script@v7
        with:
          script: |
            try {
              const prNumber = context.issue.number;
              const prAuthor = context.payload.pull_request.user.login;
              
              console.log(`Assigning PR #${prNumber} to author: ${prAuthor}`);
              
              await github.rest.issues.addAssignees({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: prNumber,
                assignees: [prAuthor]
              });
              
              console.log(`Successfully assigned PR #${prNumber} to ${prAuthor}`);
            } catch (error) {
              console.error('Failed to assign PR author:', error);
              throw error;
            }
