name: Auto Assign PR Reviewers

on:
  pull_request:
    types: [opened]

jobs:
  assign-reviewers:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Assign reviewers based on PR author
        uses: actions/github-script@v7
        with:
          script: |
            try {
              const prNumber = context.issue.number;
              const prAuthor = context.payload.pull_request.user.login;
              
              // 作成者ごとのレビューワーマッピング
              // レビュアー変更時はここを編集する
              //const reviewerMapping = {
              //  '0fuzimaru0': ['0fuzimaru0']
              //};
              const reviewerMapping = {};
              
              // マッピングにない場合は誰も指定しない
              const assignedReviewers = reviewerMapping[prAuthor] || [];
              
              console.log(`Requesting reviews for PR #${prNumber} from author: ${prAuthor}`);
              
              if (assignedReviewers.length > 0) {
                await github.rest.pulls.requestReviewers({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  pull_number: prNumber,
                  reviewers: assignedReviewers
                });
                
                console.log(`Successfully requested reviews from: ${assignedReviewers.join(', ')}`);
              } else {
                console.log(`No reviewers defined for author: ${prAuthor}. Skipping reviewer assignment.`);
              }
            } catch (error) {
              console.error('Failed to request reviews:', error);
              throw error;
            }
